### ISSUE TITLE
[Backend]  cart 모델, 시드 생성, 등록 구현

### ISSUE THREAD

**Issue by anniemon** [codestates/Meal-To-Meal#107]
### ISSUE
Group: `server`
Type: `feature`

### TODO
- [x] 카트 모델 생성
- [x] 카트 시드 생성
- [x] 카트 등록 구현

### Estimated time
`3h`
