### ISSUE TITLE
[Frontend] 가게 상세 페이지, 회원 관련 페이지 서버와 연결

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#117]
### ISSUE
Group: `client`
Type: `feature`

### TODO
- [x] 가게 상세 페이지 구현
- [x] 회원정보 수정 구현
- [x] 회원탈퇴 구현
- [x] 나눔카트 페이지 구현
- [x] 리뷰 페이지 모달 tablet, desktop 반응형 추가
- [x] 사이드바, 언더바 onClick 이벤트 추가

### Estimated time
10h
