### ISSUE TITLE
[SR] 4일차 기획 플랜

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#13]
### ISSUE
Group: `sr`
Type: `feature`
Detail: 전체적으로 SR 기획을 정리하고 마무리하는 단계입니다

### TODO
- [x] api 문서 완성하기
- [x] db 스키마 한번 더 확인하기
- [x] 스택 결정하기
- [x] to do list 작성하기
- [x] requirements 작성하기
- [x] 시스템 아키텍쳐 작성하기
- [x] 레포 WIKI 초안 작성하기
- [x] sr기획 1차 완료하고 제출완료하기

### Estimated time
10h
