### ISSUE TITLE
[Backend] user-meal 조회, 등록, 삭제

### ISSUE THREAD

**Issue by anniemon** [codestates/Meal-To-Meal#153]
### ISSUE
Group: `server`
Type: `feature`

### TODO
- [x] user-meal 조회
- [x] user-meal 등록
- [x] user-meal 삭제

### Estimated time
`4h`
