### ISSUE TITLE
[Frontend][Backend] 휴대폰 인증 구현

### ISSUE THREAD

**Issue by anniemon** [codestates/Meal-To-Meal#188]
### ISSUE
Group: `client`, `server`
Type: `feature`

### TODO
- [x] 마이페이지에서 휴대폰 인증 구현
- [x] user 테이블에 email_verified를 없애고 user_phone_number를 저장
- [x] user_phone_number가 null이면 먹기, 기부하기 방지
- [x] 마이페이지에서 인증 완료하면 다시 먹기, 기부하기 페이지로 리디렉션 (혹은 다른 방식으로 인증과 먹기-기부하기 간의 ux 최적화)

### Estimated time
`8h`
