### ISSUE TITLE
[Frontend] 랜딩페이지, 아이콘 설정

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#191]
### ISSUE
Group: `client`
Type: `feature`
Detail: 랜딩페이지, 아이콘 설정

### TODO
- [x] 랜딩페이지 만들기
- [x] 예약 내역 빈 페이지 컴포넌트로 연결하기
- [x] review 삭제 서버와 연결하기
- [x] 음식점 카테고리 아이콘 설정하기
- [x] 지도 마커 핀 아이콘 변경하기

### Estimated time
8h
