### ISSUE TITLE
[Frontend]기부현황 페이지와 alert 창

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#205]
### ISSUE
Group: `client`
Type: `feature`
Detail: 기부현황 페이지와 alert 창

### TODO
- [x] 기부현황 페이지 만들기
- [x] 기부현황 페이지 css 만들기
- [x] 기부현황 페이지 서버와 연결하기
- [x] 페이지 간 연결되는 alert창 없는 부분 만들기

### Estimated time
6h
