### ISSUE TITLE
[Frontend] Mypage, PhoneVerificationModal 상세 수정, 가게 상세 페이지 리뷰 연결

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#234]
### ISSUE
Group: `client`
Type: `feature`
Detail: Mypage, PhoneVerificationModal 상세 수정, 가게 상세 페이지 리뷰 연결

### TODO
- [x] Mypage 닉네임 수정, 비밀번호 수정 부분 css 상세하게 수정 
- [x] PhoneVerificationModal css tablet, desktop 버전 완성하기
- [x] PhoneVerificationModal res에 따른 상태메세지, alert창 띄우기
- [x] 가게 상세 페이지 리뷰내역 연결하기

### Estimated time
6h
