### ISSUE TITLE
[Frontend] 지도 마커 수정, 글씨체, 시드 파일 만들기

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#251]
### ISSUE
Group: `client`
Type: `feature`
Detail: fix actions from client redux

### TODO
- [x] 메인 글씨체 정해서 바꾸기
- [x] 지도에 띄우는 마커 핀 변경하기
- [x] 시드 파일 만들기

### Estimated time
- 5h
