### ISSUE TITLE
[Frontend] 사장님 가게 페이지 연결

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#265]
### ISSUE
Group: `client`
Type: `feature`
Detail: fix actions from client redux

### TODO
- [x] 사장님 페이지 user-meal 서버와 연결하기
- [x] 사장님이 자기 음식점에서 '먹기' 눌렀을 때 반응
- [x] 기부하기 누르면 얼럿 창 띄우기
- [x] 사장님 가게 없을 때 정보 등록하기 연결
- [x] 사장님 페이지 수정하기 연결하기

### Estimated time
8h
