### ISSUE TITLE
[Frontend][Backend] 마지막 배포 전 수정 및 체크 단계

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#307]
### ISSUE
Group: `client`, `server`
Type: `bug`, `feature`, `delete`
Detail: 마지막 배포 전 수정 및 체크 단계

### TODO
- [x] 구현된 기능들 총 점검하기
- [x] 배포된 후 기능 총 점검하기
- [x] css 확인 후 수정하기
- [x] 콘솔 및 안쓰는 변수들 지우기
- [x] Wiki 수정 및 보완하기
- [x] 발표 대본 및 예상 질문 준비하기

### Estimated time
6h
