### ISSUE TITLE
[Backend] userController 회원가입, 로그인, 로그아웃, 회원탈퇴

### ISSUE THREAD

**Issue by anniemon** [codestates/Meal-To-Meal#52]
### ISSUE
Group: `server`
Type: `feature`

### TODO
- [x] user model 생성
- [x] user seed 생성
- [x] bcrypt와 jwt를 사용한 회원가입, 로그인, 로그아웃, 회원탈퇴 구현

### Estimated time
`8h`
