### ISSUE TITLE
[SR] SR 기획 2일차, 3일차 기획 플랜

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#6]
### ISSUE
Group: sr
Type: feature
Detail: SR 기획 구체화

### TODO
- [x] Miro UI 디자인 상세하게 짜기
- [x] 프로젝트명 로고 정하기
- [x] API 문서 작성

### Estimated time
8h
