### ISSUE TITLE
[Frontend] 가게 상세 페이지, 나눔카트, 소셜 로그인 구현

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Meal-To-Meal#64]
### ISSUE
Group: `client`
Type: `feature`
Detail: 가게 상세 페이지, 나눔카트 페이지, 소셜 로그인 구현

### TODO
- [x] 가게 상세 페이지 반응형 만들기
- [x] 나눔카트 페이지 만들기
- [x] 나눔카트 페이지 반응형 만들기
- [x] 소셜 로그인 구현하기

### Estimated time
10h
