### ISSUE TITLE
[Frontend] Sharecart 아이템 연결

### ISSUE THREAD

**Issue by Hendrix1995** [codestates/Meal-To-Meal#82]
### ISSUE
Group: `client`
Type: `bug`, `feature`

### TODO
- [x] 메뉴 페이지에서 '기부하기' 를 누르면 카트에 아이템이 들어감
- [x] 이미 들어가 있는 아이템에 다시 '기부하기' 를 누르면 겟수가 하나 올라감
- [x] 아이템이 들어가면 알림으로 유저에게 알려줌

### Estimated time
`6h`
